## 1 导入Keras

In [1]:
import tensorflow as tf
from tensorflow.keras import layers
print(tf.__version__)
print(tf.keras.__version__)

E:\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


2.0.0-beta1
2.2.4-tf


## 2 构建模型
### 2.1 模型堆叠 

In [2]:
model = tf.keras.Sequential()
model.add(layers.Dense(32, activation='relu'))
model.add(layers.Dense(32, activation='relu'))
model.add(layers.Dense(10, activation='softmax'))

### 2.2网络配置
tf.keras.layers中网络配置：
activation：设置层的激活函数。此参数由内置函数的名称指定，或指定为可调用对象。默认情况下，系统不会应用任何激活函数。
kernel_initializer 和 bias_initializer：创建层权重（核和偏差）的初始化方案。此参数是一个名称或可调用对象，默认为 "Glorot uniform" 初始化器。
kernel_regularizer 和 bias_regularizer：应用层权重（核和偏差）的正则化方案，例如 L1 或 L2 正则化。默认情况下，系统不会应用正则化函数。

In [3]:
layers.Dense(32, activation='sigmoid')
layers.Dense(32, activation=tf.sigmoid)
layers.Dense(32, kernel_initializer='orthogonal')
layers.Dense(32, kernel_initializer=tf.keras.initializers.glorot_normal)
layers.Dense(32, kernel_regularizer=tf.keras.regularizers.l2(0.01))
layers.Dense(32, kernel_regularizer=tf.keras.regularizers.l1(0.01))

## 3 训练和评估
### 3.1 设置训练流程

In [4]:
model = tf.keras.Sequential()
model.add(layers.Dense(32, activation='relu'))
model.add(layers.Dense(32, activation='relu'))
model.add(layers.Dense(10, activation='softmax'))
model.compile(optimizer=tf.keras.optimizers.Adam(0.001), 
             loss=tf.keras.losses.categorical_crossentropy,
             metrics=[tf.keras.metrics.categorical_accuracy])

### 3.2 输入numpy数据

In [5]:
import numpy as np
train_x = np.random.random((1000, 72))
train_y = np.random.random((1000, 10))
val_x = np.random.random((200, 72))
val_y = np.random.random((200, 10))
model.fit(train_x, train_y, epochs=10, batch_size=100, validation_data=(val_x, val_y))

W0804 22:52:34.305140 17884 deprecation.py:323] From E:\Anaconda3\lib\site-packages\tensorflow\python\ops\math_grad.py:1250: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


Train on 1000 samples, validate on 200 samples
Epoch 1/10
1000/1000 [==============================] - 1s 518us/sample - loss: 11.4622 - categorical_accuracy: 0.1070 - val_loss: 11.5794 - val_categorical_accuracy: 0.0750
Epoch 2/10
1000/1000 [==============================] - 0s 51us/sample - loss: 11.4411 - categorical_accuracy: 0.1050 - val_loss: 11.5709 - val_categorical_accuracy: 0.0900
Epoch 3/10
1000/1000 [==============================] - 0s 47us/sample - loss: 11.4341 - categorical_accuracy: 0.1190 - val_loss: 11.5656 - val_categorical_accuracy: 0.0750
Epoch 4/10
1000/1000 [==============================] - 0s 50us/sample - loss: 11.4304 - categorical_accuracy: 0.1160 - val_loss: 11.5617 - val_categorical_accuracy: 0.0800
Epoch 5/10
1000/1000 [==============================] - 0s 53us/sample - loss: 11.4289 - categorical_accuracy: 0.1250 - val_loss: 11.5589 - val_categorical_accuracy: 0.1200
Epoch 6/10
1000/1000 [==============================] - 0s 50us/sample - loss: 11.4269 

### 3.3 tf.data输入数据

In [6]:
dataset = tf.data.Dataset.from_tensor_slices((train_x, train_y))
dataset = dataset.batch(32)
dataset = dataset.repeat()
model.fit(dataset, epochs=10, steps_per_epoch=30, validation_data=(val_x, val_y), validation_steps=3)

W0804 22:52:35.830274 17884 training_utils.py:1436] Expected a shuffled dataset but input dataset `x` is not shuffled. Please invoke `shuffle()` on input dataset.


Epoch 1/10
30/30 [==============================] - 0s 13ms/step - loss: 11.3993 - categorical_accuracy: 0.1375 - val_loss: 11.4930 - val_categorical_accuracy: 0.1050
Epoch 2/10
30/30 [==============================] - 0s 10ms/step - loss: 11.4117 - categorical_accuracy: 0.1389 - val_loss: 11.4932 - val_categorical_accuracy: 0.1100
Epoch 3/10
30/30 [==============================] - 0s 8ms/step - loss: 11.4011 - categorical_accuracy: 0.1453 - val_loss: 11.4951 - val_categorical_accuracy: 0.0950
Epoch 4/10
30/30 [==============================] - 0s 7ms/step - loss: 11.3575 - categorical_accuracy: 0.1464 - val_loss: 11.4964 - val_categorical_accuracy: 0.0900
Epoch 5/10
30/30 [==============================] - 0s 7ms/step - loss: 11.4097 - categorical_accuracy: 0.1517 - val_loss: 11.4972 - val_categorical_accuracy: 0.1050
Epoch 6/10
30/30 [==============================] - 0s 6ms/step - loss: 11.3962 - categorical_accuracy: 0.1571 - val_loss: 11.5009 - val_categorical_accuracy: 0.0900
Ep

### 3.4 评估预测

In [7]:
test_x = np.random.random((1000, 72))
test_y = np.random.random((1000, 10))
model.evaluate(test_x, test_y, batch_size=32)
test_data = tf.data.Dataset.from_tensor_slices((test_x, test_y))
test_data = test_data.batch(32).repeat()
model.evaluate(test_data, steps=30)

30/30 [==============================] - 0s 4ms/step - loss: 11.5576 - categorical_accuracy: 0.0812


[11.557552528381347, 0.08125]

In [8]:
#predict
result = model.predict(test_x, batch_size=32)
print(result)

[[0.09861725 0.09936366 0.10924117 ... 0.095795   0.08978011 0.10099507]
 [0.09774385 0.10007057 0.1054799  ... 0.1070191  0.0897495  0.09493347]
 [0.08416529 0.08979382 0.1281266  ... 0.08430692 0.08566346 0.09176555]
 ...
 [0.08788679 0.11144421 0.09417646 ... 0.11775994 0.09587049 0.09484484]
 [0.09550127 0.0948486  0.10436514 ... 0.10358349 0.09279111 0.08629732]
 [0.08221681 0.09019032 0.12323799 ... 0.06092671 0.09274279 0.13029665]]


## 4 构建高级模型
### 4.1 函数式API

In [9]:
input_x = tf.keras.Input(shape=(72,))
hidden1 = layers.Dense(32, activation='relu')(input_x)
hidden2 = layers.Dense(16, activation='relu')(hidden1)
pred = layers.Dense(10, activation='softmax')(hidden2)
model.compile(optimizer=tf.keras.optimizers.Adam(0.001),
             loss=tf.keras.losses.categorical_crossentropy,
             metrics=['accuracy'])
model.fit(train_x, train_y, batch_size=32, epochs=5)

Train on 1000 samples
Epoch 1/5
1000/1000 [==============================] - 0s 353us/sample - loss: 11.3843 - accuracy: 0.1690
Epoch 2/5
1000/1000 [==============================] - 0s 123us/sample - loss: 11.3786 - accuracy: 0.1920
Epoch 3/5
1000/1000 [==============================] - 0s 122us/sample - loss: 11.3750 - accuracy: 0.1840
Epoch 4/5
1000/1000 [==============================] - 0s 119us/sample - loss: 11.3719 - accuracy: 0.1940
Epoch 5/5
1000/1000 [==============================] - 0s 131us/sample - loss: 11.3691 - accuracy: 0.1960


### 4.2 模型子类化
通过对 tf.keras.Model 进行子类化并定义您自己的前向传播来构建完全可自定义的模型。   
在 init 方法中创建层并将它们设置为类实例的属性。   
在 call 方法中定义前向传播。

In [11]:
class MyModel(tf.keras.Model):
    def __init__(self, num_classes=10):
        super(MyModel, self).__init__(name='my_model')
        self.num_classes = num_classes
        self.layer1 = layers.Dense(32, activation='relu')
        self.layer2 = layers.Dense(num_classes, activation='softmax')
        
    def call(self, input):
        hidden1 = self.layer1(input)
        out = self.layer2(hidden1)
        return out
    
    def compute_output_shape(self, input_shape):
        shape = tf.TensorShape(input_shape).as_list()
        shape[-1] = self.num_classes
        return tf.TensorShape(shape)
    
model = MyModel(num_classes=10)
model.compile(optimizer=tf.keras.optimizers.Adam(0.001),
             loss=tf.keras.losses.categorical_crossentropy,
             metrics=['accuracy'])
model.fit(train_x, train_y, batch_size=16, epochs=5)

Train on 1000 samples
Epoch 1/5
1000/1000 [==============================] - 0s 417us/sample - loss: 11.6890 - accuracy: 0.1090
Epoch 2/5
1000/1000 [==============================] - 0s 238us/sample - loss: 11.5315 - accuracy: 0.1050
Epoch 3/5
1000/1000 [==============================] - 0s 343us/sample - loss: 11.4950 - accuracy: 0.1030
Epoch 4/5
1000/1000 [==============================] - 0s 223us/sample - loss: 11.4745 - accuracy: 0.1000
Epoch 5/5
1000/1000 [==============================] - 0s 248us/sample - loss: 11.4617 - accuracy: 0.1000


### 4.3 自定义层
通过对 tf.keras.layers.Layer 进行子类化并实现以下方法来创建自定义层：  
build：创建层的权重。使用 add_weight 方法添加权重。  
call：定义前向传播。  
compute_output_shape：指定在给定输入形状的情况下如何计算层的输出形状。 或者，可以通过实现 get_config 方法和 from_config 类方法序列化层。

In [12]:
class MyLayer(layers.Layer):
    def __init__(self, output_dim, **kwargs):
        self.output_dim = output_dim
        super(MyLayer, self).__init__(**kwargs)
        
    def build(self, input_shape):
        shape = tf.TensorShape((input_shape[1], self.output_dim))
        self.kernel = self.add_weight(name='kernel1', shape=shape, initializer='uniform', trainable=True)
        super(MyLayer, self).build(input_shape)
        
    def call(self, inputs):
        return tf.matmul(inputs, self.kernel)
    
    def compute_output_shape(self, input_shape):
        shape = tf.TensorShape(input_shape).as_list()
        shape[-1] = self.output_dim
        return tf.TensorShape(shape)
    
    def get_config(self):
        base_config = super(MyLayer, self).get_config()
        base_config['output_dim'] = self.output_dim
        return base_config
    
    @classmethod
    def from_config(cls, config):
        return cls(**config)
    
model = tf.keras.Sequential(
[    
    MyLayer(output_dim=10),
    layers.Activation('softmax')
])
model.compile(optimizer=tf.keras.optimizers.RMSprop(0.001),
             loss=tf.keras.losses.categorical_crossentropy,
             metrics=['accuracy'])

model.fit(train_x, train_y, batch_size=16, epochs=5)

Train on 1000 samples
Epoch 1/5
1000/1000 [==============================] - 0s 289us/sample - loss: 11.4475 - accuracy: 0.1060
Epoch 2/5
1000/1000 [==============================] - 0s 190us/sample - loss: 11.4378 - accuracy: 0.1310
Epoch 3/5
1000/1000 [==============================] - 0s 224us/sample - loss: 11.4348 - accuracy: 0.1230
Epoch 4/5
1000/1000 [==============================] - 0s 202us/sample - loss: 11.4283 - accuracy: 0.1080
Epoch 5/5
1000/1000 [==============================] - 0s 265us/sample - loss: 11.4246 - accuracy: 0.1340


### 4.3 回调

In [14]:
callbacks = [
    tf.keras.callbacks.EarlyStopping(patience=2, monitor='val_loss'),
    tf.keras.callbacks.TensorBoard(log_dir='.\\^alogs')
]
model.fit(train_x, train_y, batch_size=16, epochs=5, 
         callbacks=callbacks, validation_data=(val_x, val_y))

Train on 1000 samples, validate on 200 samples
Epoch 1/5


W0805 23:32:54.198908 17884 callbacks.py:241] Method (on_train_batch_end) is slow compared to the batch update (0.266849). Check your callbacks.


  16/1000 [..............................] - ETA: 16s - loss: 10.3676 - accuracy: 0.0000e+00

W0805 23:32:54.253877 17884 callbacks.py:241] Method (on_train_batch_end) is slow compared to the batch update (0.154912). Check your callbacks.


1000/1000 [==============================] - 1s 636us/sample - loss: 11.4196 - accuracy: 0.1590 - val_loss: 11.5727 - val_accuracy: 0.1100
Epoch 2/5
1000/1000 [==============================] - 0s 219us/sample - loss: 11.4177 - accuracy: 0.1490 - val_loss: 11.5752 - val_accuracy: 0.1250
Epoch 3/5
1000/1000 [==============================] - 0s 219us/sample - loss: 11.4149 - accuracy: 0.1490 - val_loss: 11.5694 - val_accuracy: 0.1400
Epoch 4/5
1000/1000 [==============================] - 0s 235us/sample - loss: 11.4116 - accuracy: 0.1440 - val_loss: 11.5744 - val_accuracy: 0.1350
Epoch 5/5
1000/1000 [==============================] - 0s 226us/sample - loss: 11.4089 - accuracy: 0.1340 - val_loss: 11.5746 - val_accuracy: 0.1200
