## 1 导入Keras

In [1]:
import tensorflow as tf
from tensorflow.keras import layers
print(tf.__version__)
print(tf.keras.__version__)

E:\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


2.0.0-beta1
2.2.4-tf


## 2 构建模型
### 2.1 模型堆叠 

In [2]:
model = tf.keras.Sequential()
model.add(layers.Dense(32, activation='relu'))
model.add(layers.Dense(32, activation='relu'))
model.add(layers.Dense(10, activation='softmax'))

### 2.2网络配置
tf.keras.layers中网络配置：
activation：设置层的激活函数。此参数由内置函数的名称指定，或指定为可调用对象。默认情况下，系统不会应用任何激活函数。
kernel_initializer 和 bias_initializer：创建层权重（核和偏差）的初始化方案。此参数是一个名称或可调用对象，默认为 "Glorot uniform" 初始化器。
kernel_regularizer 和 bias_regularizer：应用层权重（核和偏差）的正则化方案，例如 L1 或 L2 正则化。默认情况下，系统不会应用正则化函数。

In [3]:
layers.Dense(32, activation='sigmoid')
layers.Dense(32, activation=tf.sigmoid)
layers.Dense(32, kernel_initializer='orthogonal')
layers.Dense(32, kernel_initializer=tf.keras.initializers.glorot_normal)
layers.Dense(32, kernel_regularizer=tf.keras.regularizers.l2(0.01))
layers.Dense(32, kernel_regularizer=tf.keras.regularizers.l1(0.01))

## 3 训练和评估
### 3.1 设置训练流程

In [4]:
model = tf.keras.Sequential()
model.add(layers.Dense(32, activation='relu'))
model.add(layers.Dense(32, activation='relu'))
model.add(layers.Dense(10, activation='softmax'))
model.compile(optimizer=tf.keras.optimizers.Adam(0.001), 
             loss=tf.keras.losses.categorical_crossentropy,
             metrics=[tf.keras.metrics.categorical_accuracy])

### 3.2 输入numpy数据

In [5]:
import numpy as np
train_x = np.random.random((1000, 72))
train_y = np.random.random((1000, 10))
val_x = np.random.random((200, 72))
val_y = np.random.random((200, 10))
model.fit(train_x, train_y, epochs=10, batch_size=100, validation_data=(val_x, val_y))

W0804 22:52:34.305140 17884 deprecation.py:323] From E:\Anaconda3\lib\site-packages\tensorflow\python\ops\math_grad.py:1250: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


Train on 1000 samples, validate on 200 samples
Epoch 1/10
1000/1000 [==============================] - 1s 518us/sample - loss: 11.4622 - categorical_accuracy: 0.1070 - val_loss: 11.5794 - val_categorical_accuracy: 0.0750
Epoch 2/10
1000/1000 [==============================] - 0s 51us/sample - loss: 11.4411 - categorical_accuracy: 0.1050 - val_loss: 11.5709 - val_categorical_accuracy: 0.0900
Epoch 3/10
1000/1000 [==============================] - 0s 47us/sample - loss: 11.4341 - categorical_accuracy: 0.1190 - val_loss: 11.5656 - val_categorical_accuracy: 0.0750
Epoch 4/10
1000/1000 [==============================] - 0s 50us/sample - loss: 11.4304 - categorical_accuracy: 0.1160 - val_loss: 11.5617 - val_categorical_accuracy: 0.0800
Epoch 5/10
1000/1000 [==============================] - 0s 53us/sample - loss: 11.4289 - categorical_accuracy: 0.1250 - val_loss: 11.5589 - val_categorical_accuracy: 0.1200
Epoch 6/10
1000/1000 [==============================] - 0s 50us/sample - loss: 11.4269 

### 3.3 tf.data输入数据

In [6]:
dataset = tf.data.Dataset.from_tensor_slices((train_x, train_y))
dataset = dataset.batch(32)
dataset = dataset.repeat()
model.fit(dataset, epochs=10, steps_per_epoch=30, validation_data=(val_x, val_y), validation_steps=3)

W0804 22:52:35.830274 17884 training_utils.py:1436] Expected a shuffled dataset but input dataset `x` is not shuffled. Please invoke `shuffle()` on input dataset.


Epoch 1/10
30/30 [==============================] - 0s 13ms/step - loss: 11.3993 - categorical_accuracy: 0.1375 - val_loss: 11.4930 - val_categorical_accuracy: 0.1050
Epoch 2/10
30/30 [==============================] - 0s 10ms/step - loss: 11.4117 - categorical_accuracy: 0.1389 - val_loss: 11.4932 - val_categorical_accuracy: 0.1100
Epoch 3/10
30/30 [==============================] - 0s 8ms/step - loss: 11.4011 - categorical_accuracy: 0.1453 - val_loss: 11.4951 - val_categorical_accuracy: 0.0950
Epoch 4/10
30/30 [==============================] - 0s 7ms/step - loss: 11.3575 - categorical_accuracy: 0.1464 - val_loss: 11.4964 - val_categorical_accuracy: 0.0900
Epoch 5/10
30/30 [==============================] - 0s 7ms/step - loss: 11.4097 - categorical_accuracy: 0.1517 - val_loss: 11.4972 - val_categorical_accuracy: 0.1050
Epoch 6/10
30/30 [==============================] - 0s 6ms/step - loss: 11.3962 - categorical_accuracy: 0.1571 - val_loss: 11.5009 - val_categorical_accuracy: 0.0900
Ep

### 3.4 评估预测

In [7]:
test_x = np.random.random((1000, 72))
test_y = np.random.random((1000, 10))
model.evaluate(test_x, test_y, batch_size=32)
test_data = tf.data.Dataset.from_tensor_slices((test_x, test_y))
test_data = test_data.batch(32).repeat()
model.evaluate(test_data, steps=30)

30/30 [==============================] - 0s 4ms/step - loss: 11.5576 - categorical_accuracy: 0.0812


[11.557552528381347, 0.08125]

In [8]:
#predict
result = model.predict(test_x, batch_size=32)
print(result)

[[0.09861725 0.09936366 0.10924117 ... 0.095795   0.08978011 0.10099507]
 [0.09774385 0.10007057 0.1054799  ... 0.1070191  0.0897495  0.09493347]
 [0.08416529 0.08979382 0.1281266  ... 0.08430692 0.08566346 0.09176555]
 ...
 [0.08788679 0.11144421 0.09417646 ... 0.11775994 0.09587049 0.09484484]
 [0.09550127 0.0948486  0.10436514 ... 0.10358349 0.09279111 0.08629732]
 [0.08221681 0.09019032 0.12323799 ... 0.06092671 0.09274279 0.13029665]]
